OPTIONS http://localhost:8080/hello
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Access-Control-Request-Method: GET
Access-Control-Request-Headers: abc,def,123,456
Random-Header: random-value1,random-value2
Connection: keep-alive
Origin: localhost
Referer: localhost/

###
OPTIONS http://localhost:8080/hello
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Access-Control-Request-Method: GET
Access-Control-Request-Headers: abc
Access-Control-Request-Headers: def
Connection: keep-alive
Origin: localhost
Referer: localhost/